import { auth, db, storage, onAuthStateChanged, signOut, collection, getDocs, addDoc, doc, updateDoc, deleteDoc, serverTimestamp, query, orderBy, ref, uploadBytes, getDownloadURL } from "./firebase-admin.js";
const list=document.querySelector("#admin-product-list"), modal=document.querySelector("#modal-backdrop"), form=document.querySelector("#product-form");
let adminProducts=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmt=p=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(p);
async function getProducts(){const snap=await getDocs(query(collection(db,"products"),orderBy("createdAt","desc")));return snap.docs.map(d=>({id:d.id,...d.data()}));}
function render(){document.querySelector("#stat-products").textContent=adminProducts.length;document.querySelector("#stat-categories").textContent=new Set(adminProducts.map(p=>p.category||"Tanpa kategori")).size;document.querySelector("#stat-value").textContent=fmt(adminProducts.reduce((s,p)=>s+(Number(p.price)||0),0));list.innerHTML=adminProducts.map(p=>`<tr><td><div class="admin-product"><div class="admin-thumb">${p.image?`<img src="${esc(p.image)}" alt="">`:esc(p.name?.slice(0,1)||"N")}</div><div><strong>${esc(p.name)}</strong><div style="color:#999;font-size:11px">${esc(p.id)}</div></div></div></td><td>${esc(p.category||"—")}</td><td>${fmt(p.price)}</td><td>${p.badge?`<span class="badge" style="position:static">${esc(p.badge)}</span>`:"—"}</td><td><div class="table-actions"><button data-edit="${p.id}">Edit</button><button class="danger" data-delete="${p.id}">Hapus</button></div></td></tr>`).join("");const cats=[...new Set(adminProducts.map(p=>p.category||"Tanpa kategori"))];document.querySelector("#admin-categories").innerHTML=cats.map(c=>`<div class="category-card"><strong>${esc(c)}</strong><span>${adminProducts.filter(p=>p.category===c).length} produk</span></div>`).join("")}
async function refresh(){try{adminProducts=await getProducts();render()}catch(e){list.innerHTML=`<tr><td colspan="5" style="padding:30px;color:#b33">Gagal membaca Firestore: ${esc(e.message)}</td></tr>`}}
function openModal(p=null){document.querySelector("#modal-title").textContent=p?"Edit Produk":"Tambah Produk";document.querySelector("#product-id").value=p?.id||"";document.querySelector("#product-name").value=p?.name||"";document.querySelector("#product-price").value=p?.price||"";document.querySelector("#product-category").value=p?.category||"";document.querySelector("#product-badge").value=p?.badge||"";document.querySelector("#product-image").value=p?.image||"";document.querySelector("#product-description").value=p?.description||"";document.querySelector("#product-stock").value=p?.stock??0;document.querySelector("#product-file").value="";modal.classList.add("show")}
function closeModal(){modal.classList.remove("show")}
document.querySelector("#add-product").onclick=()=>openModal();document.querySelector("#close-modal").onclick=closeModal;document.querySelector("#cancel-modal").onclick=closeModal;
document.querySelector("#logout").onclick=async()=>{await signOut(auth);location.href="admin-login.html"};
form.addEventListener("submit",async e=>{e.preventDefault();const id=document.querySelector("#product-id").value;const file=document.querySelector("#product-file").files[0];const data={name:document.querySelector("#product-name").value.trim(),price:Number(document.querySelector("#product-price").value),category:document.querySelector("#product-category").value.trim(),badge:document.querySelector("#product-badge").value||null,image:document.querySelector("#product-image").value.trim()||null,description:document.querySelector("#product-description").value.trim(),stock:Number(document.querySelector("#product-stock").value)||0,updatedAt:serverTimestamp()};try{if(file){const imageRef=ref(storage,`products/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`);await uploadBytes(imageRef,file);data.image=await getDownloadURL(imageRef)}if(id)await updateDoc(doc(db,"products",id),data);else await addDoc(collection(db,"products"),{...data,createdAt:serverTimestamp()});closeModal();await refresh()}catch(err){alert("Gagal menyimpan: "+err.message)}});
list.addEventListener("click",async e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]");if(edit){const p=adminProducts.find(x=>x.id===edit.dataset.edit);if(p)openModal(p)}if(del){const p=adminProducts.find(x=>x.id===del.dataset.delete);if(p&&confirm(`Hapus "${p.name}"?`)){try{await deleteDoc(doc(db,"products",p.id));await refresh()}catch(err){alert("Gagal menghapus: "+err.message)}}}});
onAuthStateChanged(auth,user=>{if(!user){location.href="admin-login.html";return}document.querySelector("#admin-email").textContent=user.email||"Admin";refresh()});
